genesis_file = "dev/test_genesis.json"

[network]
listen_port = 9001
listen_addr = "127.0.0.1"
bootstrap_peers = []
max_peers = 50

[storage]
db_path = "test_node_1_db"
create_if_missing = true

[consensus]
block_interval = 3
max_txs_per_block = 5

[validator]
enabled = true
private_key_path = "dev/node1-validator.key"
